# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from GUI.AutomaticFilm import Ui_AutomaticFilmWindow
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    MainWindow = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(770, 460)
        MainWindow.setFixedSize(773,460)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 110, 769, 78))
        font = QtGui.QFont()
        font.setFamily("Hollywood Hills")
        font.setPointSize(45)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:rgba(255, 255, 255, 0);\n"
"color:rgb(255, 255, 255);\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 300, 773, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255)")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalWidget.setGeometry(QtCore.QRect(0, 349, 771, 61))
        font = QtGui.QFont()
        font.setKerning(True)
        self.horizontalWidget.setFont(font)
        self.horizontalWidget.setAutoFillBackground(False)
        self.horizontalWidget.setStyleSheet("background-color:rgba(255, 255, 255, 0)")
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout.setContentsMargins(100, 10, 100, 10)
        self.horizontalLayout.setSpacing(50)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.film_button = QtWidgets.QPushButton(self.horizontalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.film_button.sizePolicy().hasHeightForWidth())
        self.film_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.film_button.setFont(font)
        self.film_button.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-color: rgb(255, 255, 255);\n"
"border-radius: 8px;\n"
"border-width: 1px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton::hover{\n"
"background-color:white;\n"
"color: black;\n"
"}\n"
"QPushButton::pressed{\n"
"border-color: black;\n"
"border-width: 3px;\n"
"}")
        self.film_button.setObjectName("film_button")
        self.horizontalLayout.addWidget(self.film_button)
        self.random_button = QtWidgets.QPushButton(self.horizontalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.random_button.sizePolicy().hasHeightForWidth())
        self.random_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.random_button.setFont(font)
        self.random_button.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-color: rgb(255, 255, 255);\n"
"border-radius: 8px;\n"
"border-width: 1px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton::hover{\n"
"background-color:white;\n"
"color: black;\n"
"}\n"
"QPushButton::pressed{\n"
"border-color: black;\n"
"border-width: 3px;\n"
"}")
        self.random_button.setObjectName("random_button")
        self.horizontalLayout.addWidget(self.random_button)
        self.vector_button = QtWidgets.QPushButton(self.horizontalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vector_button.sizePolicy().hasHeightForWidth())
        self.vector_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.vector_button.setFont(font)
        self.vector_button.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-color: rgb(255, 255, 255);\n"
"border-radius: 8px;\n"
"border-width: 1px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton::hover{\n"
"background-color:white;\n"
"color: black;\n"
"}\n"
"QPushButton::pressed{\n"
"border-color: black;\n"
"border-width: 3px;\n"
"}")
        self.vector_button.setObjectName("vector_button")
        self.horizontalLayout.addWidget(self.vector_button)
        self.horizontalLayout.setStretch(0, 60)
        self.horizontalLayout.setStretch(1, 40)
        self.horizontalLayout.setStretch(2, 60)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(590, 440, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:white;")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

#--------- Actions
        #self.vector_button.clicked.connect(self.open_AutomaticFilms)
        self.film_button.clicked.connect(self.open_AutomaticFilms)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.MainWindow = MainWindow

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Menu"))
        self.label.setText(_translate("MainWindow", "Python Movie Maker"))
        self.label_2.setText(_translate("MainWindow", "select option"))
        self.film_button.setText(_translate("MainWindow", "Automatic Movie Edit"))
        self.random_button.setText(_translate("MainWindow", "Random Movie"))
        self.vector_button.setText(_translate("MainWindow", "Vector-music-movie"))
        self.label_3.setText(_translate("MainWindow", "by Bartlomiej Kopysc 2021"))

    def open_AutomaticFilms(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_AutomaticFilmWindow()
        self.ui.setupUi(self.window)
        self.MainWindow.hide()
        self.window.show()

    def execute(self):
        import sys
        app = QtWidgets.QApplication(sys.argv)
        self.MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(self.MainWindow)
        self.MainWindow.show()
        sys.exit(app.exec_()) 

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
    
